spring:
  application:
    name: spacecatsmarket
  docker:
    compose:
      enabled: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8088

application:
  feature:
    cosmo-cats: true
    admin-operation: true
